version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: liftup-postgres
    environment:
      POSTGRES_DB: liftup
      POSTGRES_USER: liftup_user
      POSTGRES_PASSWORD: liftup_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: liftup-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@liftup.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: liftup-backend-dev
    environment:
      DATABASE_URL: postgresql://liftup_user:liftup_password@postgres:5432/liftup?schema=public
      JWT_SECRET: liftup-super-secret-jwt-key-2024
      NODE_ENV: development
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 